<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitba80a18fce1f944ca7dd0f78ccdc7508
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\Process\\' => 26,
        ),
        'P' => 
        array (
            'PhpDbCloud\\' => 11,
        ),
        'L' => 
        array (
            'League\\MimeTypeDetection\\' => 25,
            'League\\Flysystem\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'PhpDbCloud\\' => 
        array (
            0 => __DIR__ . '/..' . '/davmixcool/php-dbcloud/src',
        ),
        'League\\MimeTypeDetection\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/mime-type-detection/src',
        ),
        'League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitba80a18fce1f944ca7dd0f78ccdc7508::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitba80a18fce1f944ca7dd0f78ccdc7508::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitba80a18fce1f944ca7dd0f78ccdc7508::$classMap;

        }, null, ClassLoader::class);
    }
}
